spring:
  rabbitmq:
    addresses: 192.168.99.100
    port: 5672
    username: guest
    password: guest
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1/springcloud_sell?serverTimezone=UTC&characterEncoding=utf-8&useSSL=False
    username: zxy
    password: 940213
  jpa:
    show-sql: true
server:
  port: 8082
girl:
  name: lili
  age: 20
