spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/springcloud_sell?serverTimezone=UTC&characterEncoding=utf-8&useSSL=false
    username: zxy
    password: 940213
  jpa:
    show-sql: true
  rabbitmq:
    host: 192.168.99.100
    port: 5672
    username: guest
    password: guest
server:
  port: 8081
